Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,36 +1,67 @@
-name: Analyze pull request
-
+name: Check testcases and quality gate status
+ 
 on:
   pull_request:
     branches:
-      - '*'
-
+      - "*"
+ 
 jobs:
-  build:
-
+  sonarqube-analysis:
     runs-on: ubuntu-latest
-
+ 
     steps:
-      - name: Setup sonarqube
-        uses: warchant/setup-sonar-scanner@v1
-
-      - name: 'Checkout repository on branch: ${{ github.REF }}'
+      - name: Checkout code
         uses: actions/checkout@v2
+ 
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
         with:
-          ref: ${{ github.HEAD_REF }}
-
-      - name: Retrieve entire repository history
+          node-version: "14"
+ 
+      - name: Set branch name
+        id: set_branch
         run: |
-          git fetch --prune --unshallow
-      - name: Run an analysis of the PR
-        env:
-          # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: sonar-scanner
-          -Dsonar.host.url='http://sonarqube.kcspl.in:9000/'
-          -Dsonar.login='89f09c21d9b7f2f8e67b98200b5772794b4c2872'
-          -Dsonar.projectKey='kcs-arpitdixit_branchname'
-          -Dsonar.pullrequest.key=${{ github.event.number }}
-          -Dsonar.pullrequest.branch=${{ github.HEAD_REF }}
-          -Dsonar.pullrequest.base=${{ github.BASE_REF }}
-          -Dsonar.pullrequest.github.repository=${{ github.repository }}
+          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
+          BRANCH_NM=${GITHUB_HEAD_REF}
+          else
+          BRANCH_NM=$(echo ${GITHUB_REF#refs/heads/})
+          fi
+          echo "BRANCH_NAME=((${BRANCH_NE}))" >> $GITHUB_ENV
+      - name: Scanning the project with sonarQube scanner
+        run: |
+          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
+            BRANCH_NAME=${GITHUB_HEAD_REF}
+          else
+            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
+          fi
+            echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+          npm install -g sonarqube-scanner
+            sonar-scanner \
+              -Dsonar.host.url='http://sonarqube.kcspl.in:9000/' \
+              -Dsonar.projectKey='kcs-arpitdixit_branchname' \
+              -Dsonar.login=cab872eb9f133e53532de29a9fb7bec0cd9b61e2 \
+              -Dsonar.branch.name=$BRANCH_NAME
+ 
+      - name: identify SonarQube Quality Gate status
+        id: quality_gate_status
+        run: |
+          echo "Identifying quality gate status..."
+          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
+            BRANCH_NAME=${GITHUB_HEAD_REF}
+          else
+            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
+          fi
+            echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+ 
+          STATUS=$(curl -s "http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=kcs-arpitdixit_branchname&branch=${BRANCH_NAME}" -u "89f09c21d9b7f2f8e67b98200b5772794b4c2872" | jq -r '.projectStatus.status')
+          echo "Quality Gate Status for branch $BRANCH_NAME: $STATUS"
+          echo "QUALITY_GATE_STATUS=$STATUS" >> $GITHUB_ENV
+ 
+      - name: Check Quality Gate status
+        run: |
+          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
+            echo "SonarQube Quality Gate Failed for branch $BRANCH_NAME!!"
+            exit 1
+          else
+            echo "SonarQube Quality Gate passed for branch $BRANCH_NAME!!"
+          fi
